### ISSUE TITLE
Global HYCOM models

### ISSUE THREAD

**Issue by ocefpaf** [SECOORA/skill_score#199]
We find [http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global.html](http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global.html) via the CSW search. However, as @rsignell-usgs mentioned, it would be interesting to have [http://tds.hycom.org/thredds/dodsC/glb_analysis.html](http://tds.hycom.org/thredds/dodsC/glb_analysis.html) too.

**Comment by ocefpaf** [comment]
@rsignell-usgs do you have any ideas why we do not pick http://tds.hycom.org/thredds/dodsC/glb_analysis up in the catalog search?

**Comment by ocefpaf** [comment]
@rsignell-usgs mention in #227 

> @ocefpaf , does the search pick up the [HYCOM from oceannomads](http://ecowatch.ncddc.noaa.gov/global-hycom/)?

**Comment by rsignell-usgs** [comment]
@jcothran or @kwilcox, SECOORA now has a WAF, right?   
Since the global hycom products at 
http://tds.hycom.org/thredds/dodsC/glb_analysis
are from FSU, perhaps you could crawl the thredds catalogs and add to the SECOORA WAF so that these get picked up?

**Comment by rsignell-usgs** [comment]
@jcothran , ping!

**Comment by jcothran** [comment]
@rsignell-usgs @ocefpaf @kwilcox

Hey Rich,

SECOORA has a WAF endpoint, if you want to add xml records to be pulled from there as a proxy for global models or whatever else you have in mind, I'm ok with but seems like more of an IOOS catalog level issue(maybe there should be an IOOS WAF catch-all for super-regional, global models, etc) than an RA-specific one.  In the meantime if you want to send me the xml files to post at the SECOORA WAF send the documents to my gmail account and I can upload.

Thanks

**Comment by ocefpaf** [comment]
This issue is no longer pertinent since a lot have change since I opened it.
